### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ajhalls** [PhilipKolar/Uniform-Monitor-Borders#1]
Just curious what the status is on this project? Looking for something that can solve the issue of having a 4K monitor vertical next to a 1080P monitor. This looked promising, but it was never released:
https://www.youtube.com/watch?v=7bewSC1ugyU

Hoping your solution will be able to help me.

**Comment by PhilipKolar** [comment]
Hi @ajhalls, thanks for asking. Unfortunately I abandoned this project around the time I started working full time, and it isn't much more than a concept as-is. I'm not sure where I can recommend you get this functionality, I suspect Synergy can be configured to do it but probably only for remote monitors.
